config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :users, only: [:new, :create]
  resources :tasks do
    member do
      patch :update_status
    end

    collection do
      get :completed
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  STATUS  = ['Backlog', 'In-progress', 'Done'].freeze

  validates :title, presence: true,
                    length: { minimum: 5, maximum: 50 }
  validates :deadline, presence: true
  validates :status, inclusion: { in: STATUS }

  def self.statuses
    STATUS
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks

  validates :name, presence: true,
                    length: { minimum: 3, maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  has_secure_password

  def self.digest(string)
    if ActiveModel::SecurePassword.min_cost
      cost = BCrypt::Engine::MIN_COST
    else
      cost = BCrypt::Engine.cost
    end
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # skip_before_action :require_user

  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'Logged in successfully'
      redirect_to tasks_path
    else
      flash.now[:alert] = 'Invalid email or password. Try again'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged out successfully'
    redirect_to root_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_statuses, only: [:new, :create, :edit, :update]
  before_action :set_task, only: [:edit, :update, :destroy, :update_status]
  before_action :require_user

  def index
    @tasks = current_user.tasks.where.not(status: "Done")
  end

  def new
    @task = current_user.tasks.build
  end

   def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:notice] = "Task successfully created"
      redirect_to tasks_path
    else
      flash[:alert] = "Something went wrong"
      render 'new'
    end
  end

  def edit; end

  def update
    if @task.update(task_params)
      flash[:notice] = "Task updated successfully"
      redirect_to tasks_path
    else
      flash[:alert] = "Something went wrong try again"
      render :edit
    end
  end

  def destroy
    @task.destroy
    flash[:notice] = "Task deleted successfully"
    redirect_to tasks_path
  end

  def update_status
    if @task.update(task_status_params)
      if @task.status == "Done"
        flash[:notice] = "Task status was successfully updated."
        redirect_to completed_tasks_path
      else
        redirect_to tasks_path, notice: 'Task status was successfully updated.'
      end
    else
      redirect_to tasks_path, alert: 'Failed to update task status.'
    end
  end

  def completed
    @tasks = current_user.tasks.where(status: "Done")
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :status, :deadline)
  end

  def set_statuses
    @statuses = ['Backlog', 'In-progress', 'Done']
  end

  def task_status_params
    params.require(:task).permit(:status)
  end

  def require_user
    redirect_to login_path unless current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You have signed up successfully"
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center">
    <h1 class="display-4">Welcome to MyTasks !!!</h1>
    <p class="lead">This is the only tool You will need to manage all your tasks.</p>
    <% if logged_in? %>
      <p class="lead">
        <% if current_user.tasks.where.not(status: "Done").present? %>
          <%= link_to "All tasks", tasks_path %>
        <% else %>
          <%= link_to "Completed", completed_tasks_path %>
        <% end %>
      </p>
      <p class="lead">
          <%= button_to 'Logout!', logout_path, class: 'btn btn-success btn-md', method: :delete %>
      </p>
    <% else %>
      <p class="lead">
          <%= link_to 'Sign up!', new_user_path, class: 'btn btn-success btn-lg' %>
      </p>
      <p>Already have an account?</p>
      <p class="lead">
          <%= link_to 'Login!', login_path, class: 'btn btn-success btn-md' %>
      </p>
      <hr/>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <%= link_to "MyTasks", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "New task", new_task_path, class: "nav-link" %>
      </li>
      <% if logged_in?%>
        <li class="nav-item active">
          <%= link_to "Completed Tasks", completed_tasks_path, class: "nav-link" %>
        </li>
          <li class="nav-item active">
          <%= link_to "Pending Tasks", tasks_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= button_to "Log Out", logout_path, method: "delete", data: { turbo_action: :delete}, class: "nav-link" %>
        </li>
       <% else %>
        <li class="nav-item">
          <%= link_to "Log in now!", login_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTasks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body>
    <%= render partial: "layouts/navbar"%>
    <%= render partial: "shared/flash" %>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_errors.html.erb
<div class="container">
  <% if obj.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading">The following errors prevented the action from being performed</h4>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/shared/_flash.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/tasks/_form.html.erb
<%= render "shared/errors", obj: @task %>
<%= form_with model: @task, local: true, data: { turbo: false } do |form| %>
  <div class="form-group row mt-3">
    <%= form.label :title, "Title" %>
    <%= form.text_field :title, class: "form-control", placeholder: "Enter title" %>
  </div>
  <div class="form-group row mt-3">
    <%= form.label :description, "Description" %>
    <%= form.text_field :description, class: "form-control", placeholder: "Enter description" %>
  </div>
  <div class="form-group row mt-3">
    <%= form.label :deadline, "Deadline" %>
    <%= form.date_field :deadline, class: "form-control" %>
  </div>
  <div class="form-group row mt-3">
    <%= form.label :status, "Status"%>
    <%= form.select :status, options_for_select(@statuses, @task.status), {}, { class: "form-control" } %>
  </div>
  <div class=" form-group row mt-3">
  <%= form.submit (@task.new_record? ? "Create" : "Update"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/completed.html.erb
<h1>Tasks</h1>
<%= link_to 'New Task', new_task_path, class: 'btn btn-primary' %>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr id="<%= dom_id(task) %>">
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/completed_tasks.html.erb
<h1>Tasks</h1>
<%= link_to 'New Task', new_task_path, class: 'btn btn-primary' %>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr id="<%= dom_id(task) %>">
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-5">
      <div class="mt-3">
        <h1>Edit Task</h1>
      </div>
        <%= render "form"%>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<h1>Tasks</h1>
<%= link_to 'New Task', new_task_path, class: 'btn btn-primary' %>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th>Deadline</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr id="<%= dom_id(task) %>">
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td>
          <%= form_with model: task, url: update_status_task_path(task), method: :patch, data: { turbo_frame: dom_id(task) } do |form| %>
            <%= form.select :status, Task.statuses.map { |status| [status.humanize, status] }, {}, onchange: 'this.form.requestSubmit()' %>
          <% end %>
        </td>
        <td><%= task.deadline %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-5">
      <div class="mt-3">
        <h1>Create new Task</h1>
      </div>
      <%= render "shared/errors", obj: @task %>
      <%= form_with model: @task, url: tasks_path, local: true, data: { turbo: false } do |form| %>
        <div class="form-group row mt-3">
          <%= form.label :title, "Title" %>
          <%= form.text_field :title, class: "form-control", placeholder: "Enter title" %>
        </div>
        <div class="form-group row mt-3">
          <%= form.label :description, "Description" %>
          <%= form.text_field :description, class: "form-control", placeholder: "Enter description" %>
        </div>
        <div class="form-group row mt-3">
          <%= form.label :status, "Status"%>
          <%= form.select :status, @statuses, {}, { class: "form-control" } %>
        </div>
        <div class=" form-group row mt-3">
        <%= form.submit "Create", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-5">
      <div class="mt-3">
        <h1>Sign Up</h1>
      </div>
      <%= render "shared/errors", obj: @user %>
      <%= form_with model: @user, url: users_path, local: true, data: { turbo: false } do |form| %>
        <div class="form-group row mt-3">
          <%= form.label :name, "Name" %>
          <%= form.text_field :name, class: "form-control", placeholder: "Enter your name" %>
        </div>
        <div class="form-group row mt-3">
          <%= form.label :email, "Email" %>
          <%= form.text_field :email, class: "form-control", placeholder: "Enter your email address" %>
        </div>
        <div class="form-group row mt-3">
          <%= form.label :password, "Password"%>
          <%= form.password_field :password, class: "form-control", placeholder: "Enter your password" %>
        </div>
        <div class="form-group row mt-3">
          <%= form.label :password_confirmation, "Confirm password" %>
          <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Please enter the password again" %>
        </div>
        <div class=" form-group row mt-3">
        <%= form.submit "Sign Up", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>